Map<String, List<String>> peruDepartmentsProvinces = {
  // Aquí va el mapa de departamentos y sus provincias
  'Amazonas': [
    'Chachapoyas',
    'Bagua',
    'Bongará',
    'Condorcanqui',
    'Luya',
    'Rodríguez de Mendoza',
    'Utcubamba'
  ],
  'Áncash': [
    'Huaraz',
    'Aija',
    'Antonio Raymondi',
    'Asunción',
    'Bolognesi',
    'Carhuaz',
    'Carlos Fermín Fitzcarrald',
    'Casma',
    'Corongo',
    'Huari',
    'Huarmey',
    'Huaylas',
    'Mariscal Luzuriaga',
    'Ocros',
    'Pallasca',
    'Pomabamba',
    'Recuay',
    'Santa',
    'Sihuas',
    'Yungay'
  ],
  'Apurímac': [
    'Abancay',
    'Andahuaylas',
    'Antabamba',
    'Aymaraes',
    'Cotabambas',
    'Chincheros',
    'Grau'
  ],
  'Arequipa': [
    'Arequipa',
    'Camaná',
    'Caravelí',
    'Castilla',
    'Caylloma',
    'Condesuyos',
    'Islay',
    'La Unión'
  ],
  'Ayacucho': [
    'Huamanga',
    'Cangallo',
    'Huanca Sancos',
    'Huanta',
    'La Mar',
    'Lucanas',
    'Parinacochas',
    'Páucar del Sara Sara',
    'Sucre',
    'Víctor Fajardo',
    'Vilcas Huamán'
  ],
  'Cajamarca': [
    'Cajamarca',
    'Cajabamba',
    'Celendín',
    'Chota',
    'Contumazá',
    'Cutervo',
    'Hualgayoc',
    'Jaén',
    'San Ignacio',
    'San Marcos',
    'San Miguel',
    'San Pablo',
    'Santa Cruz'
  ],
  'Callao': ['Callao'],
  'Cusco': [
    'Cusco',
    'Acomayo',
    'Anta',
    'Calca',
    'Canas',
    'Canchis',
    'Chumbivilcas',
    'Espinar',
    'La Convención',
    'Paruro',
    'Paucartambo',
    'Quispicanchi',
    'Urubamba'
  ],
  'Huancavelica': [
    'Huancavelica',
    'Acobamba',
    'Angaraes',
    'Castrovirreyna',
    'Churcampa',
    'Huaytará',
    'Tayacaja'
  ],
  'Huánuco': [
    'Huánuco',
    'Ambo',
    'Dos de Mayo',
    'Huacaybamba',
    'Huamalíes',
    'Leoncio Prado',
    'Marañón',
    'Pachitea',
    'Puerto Inca',
    'Lauricocha',
    'Yarowilca'
  ],
  'Ica': ['Ica', 'Chincha', 'Nazca', 'Palpa', 'Pisco'],
  'Junín': [
    'Huancayo',
    'Concepción',
    'Chanchamayo',
    'Jauja',
    'Junín',
    'Satipo',
    'Tarma',
    'Yauli',
    'Chupaca'
  ],
  'La Libertad': [
    'Trujillo',
    'Ascope',
    'Bolívar',
    'Chepén',
    'Julcán',
    'Otuzco',
    'Pacasmayo',
    'Pataz',
    'Sánchez Carrión',
    'Santiago de Chuco',
    'Gran Chimú',
    'Viru'
  ],
  'Lambayeque': ['Chiclayo', 'Ferreñafe', 'Lambayeque'],
  'Lima': [
    'Lima',
    'Barranca',
    'Cajatambo',
    'Canta',
    'Cañete',
    'Huaral',
    'Huarochirí',
    'Huaura',
    'Oyón',
    'Yauyos'
  ],
  'Loreto': [
    'Iquitos',
    'Alto Amazonas',
    'Datem del Marañón',
    'Loreto',
    'Mariscal Ramón Castilla',
    'Maynas',
    'Putumayo',
    'Requena',
    'Ucayali'
  ],
  'Madre de Dios': ['Tambopata', 'Manu', 'Tahuamanu'],
  'Moquegua': ['Mariscal Nieto', 'General Sánchez Cerro', 'Ilo'],
  'Pasco': ['Pasco', 'Daniel Alcides Carrión', 'Oxapampa'],
  'Piura': [
    'Piura',
    'Ayabaca',
    'Huancabamba',
    'Morropón',
    'Paita',
    'Sullana',
    'Talara',
    'Sechura'
  ],
  'Puno': [
    'Puno',
    'Azángaro',
    'Carabaya',
    'Chucuito',
    'El Collao',
    'Huancané',
    'Lampa',
    'Melgar',
    'Moho',
    'San Antonio de Putina',
    'San Román',
    'Sandia',
    'Yunguyo'
  ],
  'San Martín': [
    'Moyobamba',
    'Bellavista',
    'El Dorado',
    'Huallaga',
    'Lamas',
    'Mariscal Cáceres',
    'Picota',
    'Rioja',
    'San Martín',
    'Tocache'
  ],
  'Tacna': ['Tacna', 'Candarave', 'Jorge Basadre', 'Tarata'],
  'Tumbes': ['Tumbes', 'Contralmirante Villar', 'Zarumilla'],
  'Ucayali': ['Coronel Portillo', 'Atalaya', 'Padre Abad', 'Purús']
};

Map<String, List<String>> peruProvincesDistricts = {
  // Aquí va el mapa de provincias y sus distritos
  // Amazonas
  'Chachapoyas': [
    'Chachapoyas',
    'Asunción',
    'Balsas',
    'Cheto',
    'Chiliquín',
    'Chuquibamba',
    'Granada',
    'Huancas',
    'La Jalca',
    'Leimebamba',
    'Levanto',
    'Magdalena',
    'Mariscal Castilla',
    'Molinopampa',
    'Montevideo',
    'Olleros',
    'Quinjalca',
    'San Francisco de Daguas',
    'San Isidro de Maino',
    'Soloco',
    'Sonche'
  ],
  'Bagua': ['Aramango', 'Bagua', 'Copallín', 'El Parco', 'Imaza', 'La Peca'],
  'Bongará': [
    'Chisquilla',
    'Churuja',
    'Corosha',
    'Cuispes',
    'Florida',
    'Jazán',
    'Jumbilla',
    'Recta',
    'San Carlos',
    'Shipasbamba',
    'Valera',
    'Yambrasbamba'
  ],
  'Condorcanqui': ['El Cenepa', 'Nieva', 'Río Santiago'],
  'Luya': [
    'Camporredondo',
    'Cocabamba',
    'Colcamar',
    'Conila',
    'Inguilpata',
    'Lamud',
    'Longuita',
    'Lonya Chico',
    'Luya',
    'Luya Viejo',
    'María',
    'Ocalli',
    'Ocumal',
    'Pisuquía',
    'Providencia',
    'San Cristóbal',
    'San Francisco de Yeso',
    'San Jerónimo',
    'San Juan de Lopecancha',
    'Santa Catalina',
    'Santo Tomás',
    'Tingo',
    'Trita'
  ],
  'Rodríguez de Mendoza': [
    'Chirimoto',
    'Cochamal',
    'Huambo',
    'Limabamba',
    'Longar',
    'Mariscal Benavides',
    'Milpuc',
    'Omia',
    'San Nicolás',
    'Santa Rosa'
  ],
  'Utcubamba': [
    'Bagua Grande',
    'Cajaruro',
    'Cumba',
    'El Milagro',
    'Jamalca',
    'Lonya Grande',
    'Yamon'
  ],

  // Áncash
  'Huaraz': [
    'Cochabamba',
    'Colcabamba',
    'Huanchay',
    'Independencia',
    'Jangas',
    'La Libertad',
    'Olleros',
    'Pampas',
    'Pariacoto',
    'Pira',
    'Tarica'
  ],
  'Aija': ['Aija', 'Coris', 'Huacllán', 'La Merced', 'Succha'],
  'Antonio Raymondi': [
    'Aczo',
    'Chaccho',
    'Chingas',
    'Llamellín',
    'Mirgas',
    'San Juan de Rontoy'
  ],
  'Asunción': ['Acochaca', 'Chacas'],
  'Bolognesi': [
    'Abelardo Pardo Lezameta',
    'Antonio Raymondi',
    'Aquia',
    'Cajacay',
    'Canis',
    'Chiquián',
    'Colquioc',
    'Huallanca',
    'Huasta',
    'Huayllacayán',
    'La Primavera',
    'Mangas',
    'Pacllón',
    'San Miguel de Corpanqui',
    'Ticllos'
  ],
  'Carhuaz': [
    'Acopampa',
    'Amashca',
    'Anta',
    'Ataquero',
    'Carhuaz',
    'Marcará',
    'Pariahuanca',
    'San Miguel de Aco',
    'Shilla',
    'Tinco',
    'Yungar'
  ],
  'Carlos Fermín Fitzcarrald': ['San Luis', 'San Nicolás', 'Yauya'],
  'Casma': ['Buena Vista Alta', 'Casma', 'Comandante Noel', 'Yaután'],
  'Corongo': [
    'Aco',
    'Bambas',
    'Corongo',
    'Cusca',
    'La Pampa',
    'Yanac',
    'Yupan'
  ],
  'Huari': [
    'Anra',
    'Cajay',
    'Chavín de Huantar',
    'Huacachi',
    'Huacchis',
    'Huachis',
    'Huantar',
    'Huari',
    'Masin',
    'Paucas',
    'Ponto',
    'Rahuapampa',
    'Rapayan',
    'San Marcos',
    'San Pedro de Chaná',
    'Uco'
  ],
  'Huarmey': ['Cochapeti', 'Culebras', 'Huarmey', 'Huayan', 'Malvas'],
  'Huaylas': [
    'Caraz',
    'Huallanca',
    'Huata',
    'Huaylas',
    'Mato',
    'Pamparomas',
    'Pueblo Libre',
    'Santa Cruz',
    'Santo Toribio',
    'Yuracmarca'
  ],
  'Mariscal Luzuriaga': [
    'Casca',
    'Eleazar Guzmán Barrón',
    'Fidel Olivas Escudero',
    'Llama',
    'Llumpa',
    'Lucma',
    'Musga',
    'Piscobamba'
  ],
  'Ocros': [
    'Acas',
    'Cajamarquilla',
    'Carhuapampa',
    'Cochas',
    'Congas',
    'Llipa',
    'Ocros',
    'San Cristóbal de Rajan',
    'San Pedro',
    'Santiago de Chilcas'
  ],
  'Pallasca': [
    'Bolognesi',
    'Cabana',
    'Conchucos',
    'Huacaschuque',
    'Huandoval',
    'Lacabamba',
    'Llapo',
    'Pallasca',
    'Pampas',
    'Santa Rosa',
    'Tauca'
  ],
  'Pomabamba': ['Huayllán', 'Parobamba', 'Pomabamba', 'Quinuabamba'],
  'Recuay': [
    'Catac',
    'Cotaparaco',
    'Huayllapampa',
    'Llacllin',
    'Marca',
    'Pampas Chico',
    'Pararin',
    'Recuay',
    'Tapacocha',
    'Ticapampa'
  ],
  'Santa': [
    'Cáceres del Perú',
    'Chimbote',
    'Coishco',
    'Macate',
    'Moro',
    'Nepeña',
    'Samanco',
    'Santa',
    'Nuevo Chimbote'
  ],
  'Sihuas': [
    'Acobamba',
    'Alfonso Ugarte',
    'Cashapampa',
    'Chingalpo',
    'Huayllabamba',
    'Quiches',
    'Ragash',
    'San Juan',
    'Sicsibamba',
    'Sihuas'
  ],
  'Yungay': [
    'Cascapara',
    'Mancos',
    'Matacoto',
    'Quillo',
    'Ranrahirca',
    'Shupluy',
    'Yanama',
    'Yungay'
  ],

  // Apurímac
  'Abancay': [
    'Abancay',
    'Chacoche',
    'Circa',
    'Curahuasi',
    'Huanipaca',
    'Lambrama',
    'Pichirhua',
    'San Pedro de Cachora',
    'Tamburco'
  ],
  'Andahuaylas': [
    'Andahuaylas',
    'Andarapa',
    'Chiara',
    'Huancarama',
    'Huancaray',
    'Huayana',
    'Kaquiabamba',
    'Kishuara',
    'Pacobamba',
    'Pacucha',
    'Pampachiri',
    'Pomacocha',
    'San Antonio de Cachi',
    'San Jerónimo',
    'San Miguel de Chaccrampa',
    'Santa María de Chicmo',
    'Talavera',
    'Tumay Huaraca',
    'Turpo'
  ],
  'Antabamba': [
    'Antabamba',
    'El Oro',
    'Huaquirca',
    'Juan Espinoza Medrano',
    'Oropesa',
    'Pachaconas',
    'Sabaino'
  ],
  'Aymaraes': [
    'Capaya',
    'Caraybamba',
    'Chalhuanca',
    'Chapimarca',
    'Colcabamba',
    'Cotaruse',
    'Huayllo',
    'Justo Apu Sahuaraura',
    'Lucre',
    'Pocohuanca',
    'San Juan de Chacña',
    'Sañayca',
    'Soraya',
    'Tapairihua',
    'Tintay',
    'Toraya',
    'Yanaca'
  ],
  'Cotabambas': [
    'Challhuahuacho',
    'Coyllurqui',
    'Cotabambas',
    'Haquira',
    'Mara',
    'Tambobamba'
  ],
  'Chincheros': [
    'Anco-Huallo',
    'Chincheros',
    'Cocharcas',
    'Huaccana',
    'Ocobamba',
    'Ongoy',
    'Ranracancha',
    'Uranmarca'
  ],
  'Grau': [
    'Chuquibambilla',
    'Curasco',
    'Curpahuasi',
    'Huailllati',
    'Mamara',
    'Micaela Bastidas',
    'Pataypampa',
    'Progreso',
    'San Antonio',
    'Santa Rosa',
    'Turpay',
    'Vilcabamba',
    'Virundo'
  ],

  // Arequipa
  'Arequipa': [
    'Alto Selva Alegre',
    'Arequipa',
    'Cayma',
    'Cerro Colorado',
    'Characato',
    'Chiguata',
    'Jacobo Hunter',
    'José Luis Bustamante y Rivero',
    'La Joya',
    'Mariano Melgar',
    'Miraflores',
    'Mollebaya',
    'Paucarpata',
    'Pocsi',
    'Polobaya',
    'Quequeña',
    'Sabandia',
    'Sachaca',
    'San Juan de Siguas',
    'San Juan de Tarucani',
    'Santa Isabel de Siguas',
    'Santa Rita de Siguas',
    'Socabaya',
    'Tiabaya',
    'Uchumayo',
    'Vitor',
    'Yanahuara',
    'Yarabamba',
    'Yura'
  ],
  'Camaná': [
    'Camaná',
    'José María Quimper',
    'Mariano Nicolás Valcarcel',
    'Mariscal Cáceres',
    'Nicolás de Pierola',
    'Ocoña',
    'Quilca',
    'Samuel Pastor'
  ],
  'Caravelí': [
    'Acarí',
    'Atico',
    'Atiquipa',
    'Bella Unión',
    'Cahuacho',
    'Caravelí',
    'Chala',
    'Chaparra',
    'Huanuhuanu',
    'Jaqui',
    'Lomas',
    'Quicacha',
    'Yauca'
  ],
  'Castilla': [
    'Andagua',
    'Aplao',
    'Ayo',
    'Chachas',
    'Chilcaymarca',
    'Choco',
    'Huancarqui',
    'Machaguay',
    'Orcopampa',
    'Pampacolca',
    'Tipán',
    'Uñón',
    'Uraca',
    'Viraco'
  ],
  'Caylloma': [
    'Achoma',
    'Cabanaconde',
    'Callalli',
    'Caylloma',
    'Chivay',
    'Coporaque',
    'Huambo',
    'Huanca',
    'Ichupampa',
    'Lari',
    'Lluta',
    'Maca',
    'Madrigal',
    'San Antonio de Chuca',
    'Sibayo',
    'Tapay',
    'Tisco',
    'Tuti',
    'Yanque',
    'Majes'
  ],
  'Condesuyos': [
    'Andaray',
    'Cayarani',
    'Chichas',
    'Chuquibamba',
    'Iray',
    'Río Grande',
    'Salamanca',
    'Yanaquihua'
  ],
  'Islay': [
    'Cocachacra',
    'Dean Valdivia',
    'Islay',
    'Mejia',
    'Mollendo',
    'Punta de Bombón'
  ],
  'La Unión': [
    'Alca',
    'Charcana',
    'Cotahuasi',
    'Huaynacotas',
    'Pampamarca',
    'Puyca',
    'Quechualla',
    'Sayla',
    'Tauria',
    'Tomepampa',
    'Toro'
  ],

  // Ayacucho
  'Huamanga': [
    'Acocro',
    'Acos Vinchos',
    'Carmen Alto',
    'Chiara',
    'Ocros',
    'Pacaycasa',
    'Quinua',
    'San José de Ticllas',
    'San Juan Bautista',
    'Santiago de Pischa',
    'Socos',
    'Tambillo',
    'Vinchos',
    'Jesús Nazareno',
    'Andrés Avelino Cáceres Dorregaray'
  ],
  'Cangallo': [
    'Cangallo',
    'Chuschi',
    'Los Morochucos',
    'María Parado de Bellido',
    'Paras',
    'Totos'
  ],
  'Huanca Sancos': [
    'Carapo',
    'Sacsamarca',
    'Sancos',
    'Santiago de Lucanamarca'
  ],
  'Huanta': [
    'Ayahuanco',
    'Huamanguilla',
    'Huanta',
    'Iguain',
    'Luricocha',
    'Santillana',
    'Sivia',
    'Llochegua',
    'Canayre',
    'Uchuraccay',
    'Pucacolpa',
    'Chaca'
  ],
  'La Mar': [
    'Anco',
    'Ayna',
    'Chilcas',
    'Chungui',
    'Luis Carranza',
    'San Miguel',
    'Santa Rosa',
    'Tambo',
    'Samugari',
    'Anchihuay',
    'Oronccoy'
  ],
  'Lucanas': [
    'Aucara',
    'Cabana',
    'Carmen Salcedo',
    'Chaviña',
    'Chipao',
    'Huac-Huas',
    'Laramate',
    'Leoncio Prado',
    'Llauta',
    'Lucanas',
    'Ocaña',
    'Otoca',
    'Puquio',
    'Saisa',
    'San Cristóbal',
    'San Juan',
    'San Pedro',
    'San Pedro de Palco',
    'Sancos',
    'Santa Ana de Huaycahuacho',
    'Santa Lucia'
  ],
  'Parinacochas': [
    'Coracora',
    'Chumpi',
    'Coronel Castañeda',
    'Pacapausa',
    'Pullo',
    'Puyusca',
    'San Francisco de Ravacayco',
    'Upahuacho'
  ],
  'Páucar del Sara Sara': [
    'Colta',
    'Corculla',
    'Lampa',
    'Marcabamba',
    'Oyolo',
    'Pararca',
    'Pullo',
    'Puyusca',
    'San Javier de Alpabamba',
    'Sara Sara'
  ],
  'Sucre': [
    'Belén',
    'Chalcos',
    'Chilcayoc',
    'Huacaña',
    'Morcolla',
    'Paico',
    'Querobamba',
    'San Pedro de Larcay',
    'San Salvador de Quije',
    'Santiago de Paucaray',
    'Soras'
  ],
  'Víctor Fajardo': [
    'Alcamenca',
    'Apongo',
    'Asquipata',
    'Canaria',
    'Cayara',
    'Colca',
    'Huamanquiquia',
    'Huancapi',
    'Huancaraylla',
    'Huaya',
    'Sarhua',
    'Vilcanchos'
  ],
  'Vilcas Huamán': [
    'Accomarca',
    'Carhuanca',
    'Concepción',
    'Huambalpa',
    'Independencia',
    'Saurama',
    'Vilcas Huamán',
    'Vischongo'
  ],

  // Cajamarca
  'Cajamarca': [
    'Cajamarca',
    'Asunción',
    'Chetilla',
    'Cospán',
    'Encañada',
    'Jesús',
    'Llacanora',
    'Los Baños del Inca',
    'Magdalena',
    'Matara',
    'Namora',
    'San Juan'
  ],
  'Cajabamba': ['Cachachi', 'Cajabamba', 'Condebamba', 'Sitacocha'],
  'Celendín': [
    'Celendín',
    'Chumuch',
    'Cortegana',
    'Huasmin',
    'Jorge Chávez',
    'José Gálvez',
    'La Libertad de Pallán',
    'Miguel Iglesias',
    'Oxamarca',
    'Sorochuco',
    'Sucre',
    'Utco'
  ],
  'Chota': [
    'Anguía',
    'Chadín',
    'Chalamarca',
    'Chiguirip',
    'Chimban',
    'Choropampa',
    'Chota',
    'Cochabamba',
    'Conchán',
    'Huambos',
    'Lajas',
    'Llama',
    'Miracosta',
    'Paccha',
    'Pion',
    'Querocoto',
    'San Juan de Licupis',
    'Tacabamba',
    'Tocmoche'
  ],
  'Contumazá': [
    'Chilete',
    'Contumazá',
    'Cupisnique',
    'Guzmango',
    'San Benito',
    'Santa Cruz de Toledo',
    'Tantarica',
    'Yonán'
  ],
  'Cutervo': [
    'Callayuc',
    'Choros',
    'Cujillo',
    'Cutervo',
    'La Ramada',
    'Pimpingos',
    'Querocotillo',
    'San Andrés de Cutervo',
    'San Juan de Cutervo',
    'San Luis de Lucma',
    'Santa Cruz',
    'Santo Domingo de la Capilla',
    'Santo Tomás',
    'Socota',
    'Toribio Casanova'
  ],
  'Hualgayoc': ['Bambamarca', 'Chugur', 'Hualgayoc'],
  'Jaén': [
    'Bellavista',
    'Chontali',
    'Colasay',
    'Huabal',
    'Jaén',
    'Las Pirias',
    'Pomahuaca',
    'Pucara',
    'Sallique',
    'San Felipe',
    'San José del Alto',
    'Santa Rosa'
  ],
  'San Ignacio': [
    'Chirinos',
    'Huarango',
    'La Coipa',
    'Namballe',
    'San Ignacio',
    'San José de Lourdes',
    'Tabaconas'
  ],
  'San Marcos': [
    'Chancay',
    'Eduardo Villanueva',
    'Gregorio Pita',
    'Ichocan',
    'José Manuel Quiroz',
    'José Sabogal',
    'Pedro Gálvez'
  ],
  'San Miguel': [
    'Bolívar',
    'Calquis',
    'Catilluc',
    'El Prado',
    'La Florida',
    'Llapa',
    'Nanchoc',
    'Niepos',
    'San Gregorio',
    'San Miguel',
    'San Silvestre de Cochan',
    'Tongod',
    'Unión Agua Blanca'
  ],
  'San Pablo': ['San Bernardino', 'San Luis', 'San Pablo', 'Tumbaden'],
  'Santa Cruz': [
    'Andabamba',
    'Catache',
    'Chancaybaños',
    'La Esperanza',
    'Ninabamba',
    'Pulan',
    'Santa Cruz',
    'Saucepampa',
    'Sexi',
    'Uticyacu',
    'Yauyucan'
  ],

  // Callao
  'Callao': [
    'Bellavista',
    'Callao',
    'Carmen de la Legua Reynoso',
    'La Perla',
    'La Punta',
    'Ventanilla',
    'Mi Perú'
  ],

  // Cusco
  'Cusco': [
    'Ccorca',
    'Cusco',
    'Poroy',
    'San Jerónimo',
    'San Sebastián',
    'Santiago',
    'Saylla',
    'Wanchaq'
  ],
  'Acomayo': [
    'Acomayo',
    'Acopia',
    'Acos',
    'Mosoc Llacta',
    'Pomacanchi',
    'Rondocan',
    'Sangarará'
  ],
  'Anta': [
    'Ancahuasi',
    'Anta',
    'Cachimayo',
    'Chinchaypujio',
    'Huarocondo',
    'Limatambo',
    'Mollepata',
    'Pucyura',
    'Zurite'
  ],
  'Calca': [
    'Calca',
    'Coya',
    'Lamay',
    'Lares',
    'Pisac',
    'San Salvador',
    'Taray',
    'Yanatile'
  ],
  'Canas': [
    'Checca',
    'Kunturkanki',
    'Langui',
    'Layo',
    'Pampamarca',
    'Quehue',
    'Túpac Amaru',
    'Yanaoca'
  ],
  'Canchis': [
    'Checacupe',
    'Combapata',
    'Marangani',
    'Pitumarca',
    'San Pablo',
    'San Pedro',
    'Sicuani',
    'Tinta'
  ],
  'Chumbivilcas': [
    'Capacmarca',
    'Chamaca',
    'Colquemarca',
    'Livitaca',
    'Llusco',
    'Quiñota',
    'Santo Tomás',
    'Velille'
  ],
  'Espinar': [
    'Condoroma',
    'Coporaque',
    'Espinar',
    'Ocoruro',
    'Pallpata',
    'Pichigua',
    'Suykutambo',
    'Alto Pichigua'
  ],
  'La Convención': [
    'Echarati',
    'Huayopata',
    'Inkawasi',
    'Kimbiri',
    'Maranura',
    'Ocobamba',
    'Pichari',
    'Quellouno',
    'Santa Ana',
    'Santa Teresa',
    'Vilcabamba',
    'Villa Kintiarina',
    'Villa Virgen'
  ],
  'Paruro': [
    'Accha',
    'Ccapi',
    'Colcha',
    'Huanoquite',
    'Omacha',
    'Paccaritambo',
    'Paruro',
    'Pillpinto',
    'Yaurisque'
  ],
  'Paucartambo': [
    'Caicay',
    'Challabamba',
    'Colquepata',
    'Huancarani',
    'Kosñipata',
    'Paucartambo'
  ],
  'Quispicanchi': [
    'Andahuaylillas',
    'Camanti',
    'Ccarhuayo',
    'Ccatca',
    'Cusipata',
    'Huaro',
    'Lucre',
    'Marcapata',
    'Ocongate',
    'Oropesa',
    'Quiquijana',
    'Urcos'
  ],
  'Urubamba': [
    'Chinchero',
    'Huayllabamba',
    'Machupicchu',
    'Maras',
    'Ollantaytambo',
    'Urubamba',
    'Yucay'
  ],

  // Huancavelica
  'Huancavelica': [
    'Acobambilla',
    'Acoria',
    'Conayca',
    'Cuenca',
    'Huachocolpa',
    'Huancavelica',
    'Huando',
    'Huayllahuara',
    'Izcuchaca',
    'Laria',
    'Manta',
    'Mariscal Cáceres',
    'Moya',
    'Nuevo Occoro',
    'Palca',
    'Pilchaca',
    'Vilca',
    'Yauli',
    'Ascensión'
  ],
  'Acobamba': [
    'Acobamba',
    'Andabamba',
    'Anta',
    'Caja',
    'Marcas',
    'Paucara',
    'Pomacocha',
    'Rosario'
  ],
  'Angaraes': [
    'Anchonga',
    'Callanmarca',
    'Ccochaccasa',
    'Chincho',
    'Congalla',
    'Huanca-Huanca',
    'Huayllay Grande',
    'Julcamarca',
    'Lircay',
    'San Antonio de Antaparco',
    'Santo Tomás de Pata',
    'Secclla'
  ],
  'Castrovirreyna': [
    'Arma',
    'Aurahua',
    'Capillas',
    'Castrovirreyna',
    'Chupamarca',
    'Cocas',
    'Huachos',
    'Huamatambo',
    'Mollepampa',
    'San Juan',
    'Santa Ana',
    'Tantara',
    'Ticrapo'
  ],
  'Churcampa': [
    'Anco',
    'Chinchihuasi',
    'Churcampa',
    'Cosme',
    'El Carmen',
    'La Merced',
    'Locroja',
    'Pachamarca',
    'Paucarbamba',
    'San Miguel de Mayocc',
    'San Pedro de Coris'
  ],
  'Huaytará': [
    'Ayavi',
    'Cordova',
    'Huayacundo Arma',
    'Huaytara',
    'Laramarca',
    'Ocoyo',
    'Pilpichaca',
    'Querco',
    'Quito-Arma',
    'San Antonio de Cusicancha',
    'San Francisco de Sangayaico',
    'San Isidro',
    'Santiago de Chocorvos',
    'Santiago de Quirahuara',
    'Santo Domingo de Capillas',
    'Tambo'
  ],
  'Tayacaja': [
    'Acostambo',
    'Acraquia',
    'Ahuaycha',
    'Colcabamba',
    'Daniel Hernández',
    'Huachocolpa',
    'Huaribamba',
    'Ñahuimpuquio',
    'Pampas',
    'Pazos',
    'Quishuar',
    'Salcabamba',
    'Salcahuasi',
    'San Marcos de Rocchac',
    'Surcubamba',
    'Tintay Puncu',
    'Quichuas'
  ],

  // Huánuco
  'Huánuco': [
    'Chinchao',
    'Churubamba',
    'Huánuco',
    'Margos',
    'Pillco Marca',
    'Quisqui',
    'San Francisco de Cayrán',
    'San Pedro de Chaulán',
    'Santa María del Valle',
    'Yarumayo',
    'Amarilis',
    'Lauricocha',
    'Pillco Marca'
  ],
  'Ambo': [
    'Ambo',
    'Cayna',
    'Colpas',
    'Conchamarca',
    'Huácar',
    'San Francisco',
    'San Rafael',
    'Tomay Kichwa'
  ],
  'Dos de Mayo': [
    'Chacabamba',
    'La Unión',
    'Marias',
    'Pachas',
    'Quivilla',
    'Ripan',
    'Shunqui',
    'Sillapata',
    'Yanas'
  ],
  'Huacaybamba': ['Canchabamba', 'Cochabamba', 'Huacaybamba', 'Pinra'],
  'Huamalíes': [
    'Arancay',
    'Chavín de Pariarca',
    'Jacas Grande',
    'Jircan',
    'Llata',
    'Miraflores',
    'Monzón',
    'Punchao',
    'Puños',
    'Singa',
    'Tantamayo'
  ],
  'Leoncio Prado': [
    'Castillo Grande',
    'Daniel Alomía Robles',
    'Hermilio Valdizán',
    'José Crespo y Castillo',
    'Luyando',
    'Mariano Damaso Beraun',
    'Pucayacu',
    'Rupa Rupa',
    'Santo Domingo de Anda'
  ],
  'Marañón': [
    'Cholon',
    'San Buenaventura',
    'La Morada',
    'Santa Rosa de Alto Yanajanca'
  ],
  'Pachitea': ['Chaglla', 'Molino', 'Panao', 'Umari'],
  'Puerto Inca': [
    'Codo del Pozuzo',
    'Honoria',
    'Puerto Inca',
    'Tournavista',
    'Yuyapichis'
  ],
  'Lauricocha': [
    'Baños',
    'Jesús',
    'Jivia',
    'Queropalca',
    'Rondos',
    'San Francisco de Asís',
    'San Miguel de Cauri'
  ],
  'Yarowilca': [
    'Aparicio Pomares',
    'Cahuac',
    'Chacabamba',
    'Chavinillo',
    'Choras',
    'Jacas Chico',
    'Obas',
    'Pampamarca'
  ],

  // Ica
  'Ica': [
    'Ica',
    'La Tinguiña',
    'Los Aquijes',
    'Ocucaje',
    'Pachacutec',
    'Parcona',
    'Pueblo Nuevo',
    'Salas',
    'San José de los Molinos',
    'San Juan Bautista',
    'Santiago',
    'Subtanjalla',
    'Tate',
    'Yauca del Rosario'
  ],
  'Chincha': [
    'Alto Laran',
    'Chavin',
    'Chincha Alta',
    'Chincha Baja',
    'El Carmen',
    'Grocio Prado',
    'Pueblo Nuevo',
    'San Juan de Yanac',
    'San Pedro de Huacarpana',
    'Sunampe',
    'Tambo de Mora'
  ],
  'Nazca': ['Changuillo', 'El Ingenio', 'Marcona', 'Nazca', 'Vista Alegre'],
  'Palpa': ['Llipata', 'Palpa', 'Río Grande', 'Santa Cruz', 'Tibillo'],
  'Pisco': [
    'Huancano',
    'Humay',
    'Independencia',
    'Paracas',
    'Pisco',
    'San Andrés',
    'San Clemente',
    'Tupac Amaru Inca'
  ],

  // Junín
  'Huancayo': [
    'Carhuacallanga',
    'Chacapampa',
    'Chicche',
    'Chilca',
    'Chongos Alto',
    'Chupaca',
    'Colca',
    'Cullhuas',
    'El Tambo',
    'Huacrapuquio',
    'Hualhuas',
    'Huancán',
    'Huancayo',
    'Huasicancha',
    'Huayucachi',
    'Ingenio',
    'Pariahuanca',
    'Pilcomayo',
    'Pucará',
    'Quichuay',
    'Quilcas',
    'San Agustín de Cajas',
    'San Jerónimo de Tunan',
    'San Pedro de Saño',
    'Santo Domingo de Acobamba',
    'Sapallanga',
    'Sicaya',
    'Viques'
  ],
  'Concepción': [
    'Aco',
    'Andamarca',
    'Chambara',
    'Cochas',
    'Comas',
    'Concepción',
    'Heroinas Toledo',
    'Manzanares',
    'Mariscal Castilla',
    'Matahuasi',
    'Mito',
    'Nueve de Julio',
    'Orcotuna',
    'San José de Quero',
    'Santa Rosa de Ocopa'
  ],
  'Chanchamayo': [
    'Chanchamayo',
    'Perene',
    'Pichanaqui',
    'San Luis de Shuaro',
    'San Ramón',
    'Vitoc'
  ],
  'Jauja': [
    'Acolla',
    'Apata',
    'Ataura',
    'Canchayllo',
    'Curicaca',
    'El Mantaro',
    'Huamalí',
    'Huaripampa',
    'Huertas',
    'Janjaillo',
    'Jauja',
    'Julcán',
    'Leonor Ordóñez',
    'Llocllapampa',
    'Marco',
    'Masma',
    'Masma Chicche',
    'Molinos',
    'Monobamba',
    'Muqui',
    'Muquiyauyo',
    'Paca',
    'Paccha',
    'Pancán',
    'Parco',
    'Pomacancha',
    'Ricran',
    'San Lorenzo',
    'San Pedro de Chunan',
    'Sausa',
    'Sincos',
    'Tunan Marca',
    'Yauli',
    'Yauyos'
  ],
  'Junín': ['Carhuamayo', 'Junín', 'Ondores', 'Ulcumayo'],
  'Satipo': [
    'Coviriali',
    'Llaylla',
    'Mazamari',
    'Pampa Hermosa',
    'Pangoa',
    'Río Negro',
    'Río Tambo',
    'Satipo',
    'Vizcatan del Ene'
  ],
  'Tarma': [
    'Acobamba',
    'Huaricolca',
    'Huasahuasi',
    'La Unión',
    'Palca',
    'Palcamayo',
    'San Pedro de Cajas',
    'Tapo',
    'Tarma'
  ],
  'Yauli': [
    'Chacapalpa',
    'Huay-Huay',
    'La Oroya',
    'Marcapomacocha',
    'Morococha',
    'Paccha',
    'Santa Barbara de Carhuacayan',
    'Santa Rosa de Sacco',
    'Suitucancha',
    'Yauli'
  ],
  'Chupaca': [
    'Ahuac',
    'Chongos Bajo',
    'Chupaca',
    'Huachac',
    'Huamancaca Chico',
    'San Juan de Iscos',
    'San Juan de Jarpa',
    'Tres de Diciembre',
    'Yanacancha'
  ],

  // La Libertad
  'Trujillo': [
    'El Porvenir',
    'Florencia de Mora',
    'Huanchaco',
    'La Esperanza',
    'Laredo',
    'Moche',
    'Poroto',
    'Salaverry',
    'Simbal',
    'Trujillo',
    'Victor Larco Herrera'
  ],
  'Ascope': [
    'Ascope',
    'Casa Grande',
    'Chicama',
    'Chocope',
    'Magdalena de Cao',
    'Paiján',
    'Razuri',
    'Santiago de Cao'
  ],
  'Bolívar': [
    'Bolívar',
    'Bambamarca',
    'Condormarca',
    'Longotea',
    'Uchumarca',
    'Ucuncha'
  ],
  'Chepén': ['Chepén', 'Pacanga', 'Pueblo Nuevo'],
  'Julcán': ['Calamarca', 'Carabamba', 'Huaso', 'Julcán'],
  'Otuzco': [
    'Agallpampa',
    'Charat',
    'Huaranchal',
    'La Cuesta',
    'Mache',
    'Otuzco',
    'Paranday',
    'Salpo',
    'Sinsicap',
    'Usquil'
  ],
  'Pacasmayo': [
    'Guadalupe',
    'Jequetepeque',
    'Pacasmayo',
    'San José',
    'San Pedro de Lloc'
  ],
  'Pataz': [
    'Buldibuyo',
    'Chillia',
    'Huancaspata',
    'Huaylillas',
    'Huayo',
    'Ongón',
    'Parcoy',
    'Pataz',
    'Pías',
    'Santiago de Challas',
    'Taurija',
    'Tayabamba',
    'Urpay'
  ],
  'Sánchez Carrión': [
    'Cochorco',
    'Curgos',
    'Huamachuco',
    'Marcabal',
    'Sanagorán',
    'Sarín',
    'Sartimbamba'
  ],
  'Santiago de Chuco': [
    'Angasmarca',
    'Cachicadán',
    'Mollebamba',
    'Mollepata',
    'Quiruvilca',
    'Santa Cruz de Chuca',
    'Santiago de Chuco',
    'Sitabamba'
  ],
  'Gran Chimú': ['Cascas', 'Lucma', 'Marmot', 'Sayapullo'],
  'Viru': ['Chao', 'Guadalupito', 'Viru'],

  // Lambayeque
  'Chiclayo': [
    'Chiclayo',
    'Chongoyape',
    'Eten',
    'Eten Puerto',
    'José Leonardo Ortiz',
    'La Victoria',
    'Lagunas',
    'Monsefu',
    'Nueva Arica',
    'Oyotun',
    'Picsi',
    'Pimentel',
    'Reque',
    'Santa Rosa',
    'Saña',
    'Cayalti',
    'Patapo',
    'Pomalca',
    'Pucala',
    'Tuman'
  ],
  'Ferreñafe': [
    'Cañaris',
    'Ferreñafe',
    'Incahuasi',
    'Manuel Antonio Mesones Muro',
    'Pitipo',
    'Pueblo Nuevo'
  ],
  'Lambayeque': [
    'Chochope',
    'Illimo',
    'Jayanca',
    'Lambayeque',
    'Mochumi',
    'Morrope',
    'Motupe',
    'Olmos',
    'Pacora',
    'Salas',
    'San José',
    'Tucume'
  ],

  // Lima
  'Lima': [
    'Ancón',
    'Ate',
    'Barranco',
    'Breña',
    'Carabayllo',
    'Chaclacayo',
    'Chorrillos',
    'Cieneguilla',
    'Comas',
    'El Agustino',
    'Independencia',
    'Jesús María',
    'La Molina',
    'La Victoria',
    'Lima',
    'Lince',
    'Los Olivos',
    'Lurigancho',
    'Lurín',
    'Magdalena del Mar',
    'Miraflores',
    'Pachacamac',
    'Pucusana',
    'Pueblo Libre',
    'Puente Piedra',
    'Punta Hermosa',
    'Punta Negra',
    'Rímac',
    'San Bartolo',
    'San Borja',
    'San Isidro',
    'San Juan de Lurigancho',
    'San Juan de Miraflores',
    'San Luis',
    'San Martín de Porres',
    'San Miguel',
    'Santa Anita',
    'Santa María del Mar',
    'Santa Rosa',
    'Santiago de Surco',
    'Surquillo',
    'Villa El Salvador',
    'Villa María del Triunfo'
  ],
  'Barranca': ['Barranca', 'Paramonga', 'Pativilca', 'Supe', 'Supe Puerto'],
  'Cajatambo': ['Cajatambo', 'Copa', 'Gorgor', 'Huancapon', 'Manas'],
  'Canta': [
    'Arahuay',
    'Canta',
    'Huamantanga',
    'Huaros',
    'Lachaqui',
    'San Buenaventura',
    'Santa Rosa de Quives'
  ],
  'Cañete': [
    'Asia',
    'Calango',
    'Cerro Azul',
    'Chilca',
    'Coayllo',
    'Imperial',
    'Lunahuana',
    'Mala',
    'Nuevo Imperial',
    'Pacaran',
    'Quilmana',
    'San Antonio',
    'San Luis',
    'Santa Cruz de Flores',
    'Zúñiga'
  ],
  'Huaral': [
    'Atavillos Alto',
    'Atavillos Bajo',
    'Aucallama',
    'Chancay',
    'Huaral',
    'Ihuari',
    'Lampian',
    'Pacaraos',
    'San Miguel de Acos',
    'Santa Cruz de Andamarca',
    'Sumbilca',
    'Veintisiete de Noviembre'
  ],
  'Huarochirí': [
    'Antioquía',
    'Callahuanca',
    'Carampoma',
    'Chicla',
    'Cuenca',
    'Huachupampa',
    'Huanza',
    'Huarochirí',
    'Lahuaytambo',
    'Langa',
    'Laraos',
    'Mariatana',
    'Matucana',
    'Ricardo Palma',
    'San Andrés de Tupicocha',
    'San Antonio',
    'San Bartolomé',
    'San Damian',
    'San Juan de Iris',
    'San Juan de Tantaranche',
    'San Lorenzo de Quinti',
    'San Mateo',
    'San Mateo de Otao',
    'San Pedro de Casta',
    'San Pedro de Huancayre',
    'Sangallaya',
    'Santa Cruz de Cocachacra',
    'Santa Eulalia',
    'Santiago de Anchucaya',
    'Santiago de Tuna',
    'Santo Domingo de los Olleros',
    'Surco'
  ],
  'Huaura': [
    'Ambar',
    'Caleta de Carquin',
    'Checras',
    'Huacho',
    'Hualmay',
    'Huaura',
    'Leoncio Prado',
    'Paccho',
    'Santa Leonor',
    'Santa María',
    'Sayan',
    'Vegueta'
  ],
  'Oyón': ['Andajes', 'Caujul', 'Cochamarca', 'Navan', 'Oyón', 'Pachangara'],
  'Yauyos': [
    'Alis',
    'Allauca',
    'Ayaviri',
    'Azángaro',
    'Cacra',
    'Carania',
    'Catahuasi',
    'Chocos',
    'Cochas',
    'Colonia',
    'Hongos',
    'Huampara',
    'Huancaya',
    'Huangascar',
    'Huantan',
    'Huañec',
    'Laraos',
    'Lincha',
    'Madean',
    'Miraflores',
    'Omas',
    'Putinza',
    'Quinches',
    'Quinocay',
    'San Joaquín',
    'San Pedro de Pilas',
    'Tanta',
    'Tauripampa',
    'Tomas',
    'Tupe',
    'Viñac',
    'Vitis'
  ],

  // Loreto
  'Maynas': [
    'Alto Nanay',
    'Fernando Lores',
    'Indiana',
    'Iquitos',
    'Las Amazonas',
    'Mazan',
    'Napo',
    'Punchana',
    'Putumayo',
    'San Juan Bautista',
    'Torres Causana'
  ],
  'Alto Amazonas': [
    'Balsapuerto',
    'Jeberos',
    'Lagunas',
    'Santa Cruz',
    'Teniente César López Rojas',
    'Yurimaguas'
  ],
  'Datem del Marañón': [
    'Barranca',
    'Cahuapanas',
    'Manseriche',
    'Morona',
    'Pastaza',
    'Andoas'
  ],
  'Loreto': ['Nauta', 'Parinari', 'Tigre', 'Trompeteros', 'Urarinas'],
  'Mariscal Ramón Castilla': ['Pebas', 'Ramon Castilla', 'San Pablo', 'Yavari'],
  'Putumayo': ['Putumayo', 'Rosa Panduro', 'Teniente Manuel Clavero', 'Yaguas'],
  'Requena': [
    'Alto Tapiche',
    'Capelo',
    'Emilio San Martín',
    'Maquia',
    'Puinahua',
    'Requena',
    'Saquena',
    'Soplin',
    'Tapiche',
    'Jenaro Herrera',
    'Yaquerana'
  ],
  'Ucayali': [
    'Contamana',
    'Inahuaya',
    'Padre Márquez',
    'Pampa Hermosa',
    'Sarayacu',
    'Vargas Guerra'
  ],

  // Madre de Dios
  'Tambopata': ['Inambari', 'Laberinto', 'Las Piedras', 'Tambopata'],
  'Manu': ['Fitzcarrald', 'Madre de Dios', 'Manu'],
  'Tahuamanu': ['Iberia', 'Iñapari', 'Tahuamanu'],

  // Moquegua
  'Mariscal Nieto': [
    'Carumas',
    'Cuchumbaya',
    'Moquegua',
    'Samegua',
    'San Cristóbal',
    'Torata'
  ],
  'General Sánchez Cerro': [
    'Chojata',
    'Coalaque',
    'Ichuña',
    'La Capilla',
    'Lloque',
    'Matalaque',
    'Omate',
    'Puquina',
    'Quinistaquillas',
    'Ubinas',
    'Yunga'
  ],
  'Ilo': ['El Algarrobal', 'Ilo', 'Pacocha'],

  // Pasco
  'Pasco': [
    'Chaupimarca',
    'Huachon',
    'Huariaca',
    'Huayllay',
    'Ninacaca',
    'Pallanchacra',
    'Paucartambo',
    'San Francisco de Asís de Yarusyacan',
    'Simon Bolívar',
    'Ticlacayán',
    'Tinyahuarco',
    'Vicco',
    'Yanacancha'
  ],
  'Daniel Alcides Carrión': [
    'Chacayan',
    'Goyllarisquizga',
    'Paucar',
    'San Pedro de Pillao',
    'Santa Ana de Tusi',
    'Tapuc',
    'Vilcabamba',
    'Yanahuanca'
  ],
  'Oxapampa': [
    'Chontabamba',
    'Constitución',
    'Huancabamba',
    'Oxapampa',
    'Palcazu',
    'Pozuzo',
    'Puerto Bermúdez',
    'Villa Rica'
  ],

  // Piura
  'Piura': [
    'Castilla',
    'Catacaos',
    'Cura Mori',
    'El Tallán',
    'La Arena',
    'La Unión',
    'Las Lomas',
    'Piura',
    'Tambo Grande',
    'Veintiséis de Octubre'
  ],
  'Ayabaca': [
    'Ayabaca',
    'Frias',
    'Jilili',
    'Lagunas',
    'Montero',
    'Pacaipampa',
    'Paimas',
    'Sapillica',
    'Sicchez',
    'Suyo'
  ],
  'Huancabamba': [
    'Canchaque',
    'El Carmen de la Frontera',
    'Huancabamba',
    'Huarmaca',
    'Lalaquiz',
    'San Miguel de El Faique',
    'Sondor',
    'Sondorillo'
  ],
  'Morropón': [
    'Buenos Aires',
    'Chalaco',
    'Chulucanas',
    'La Matanza',
    'Morropon',
    'Salitral',
    'San Juan de Bigote',
    'Santa Catalina de Mossa',
    'Santo Domingo',
    'Yamango'
  ],
  'Paita': [
    'Amotape',
    'Arenal',
    'Colán',
    'La Huaca',
    'Paita',
    'Tamarindo',
    'Vichayal'
  ],
  'Sullana': [
    'Bellavista',
    'Ignacio Escudero',
    'Lancones',
    'Marcavelica',
    'Miguel Checa',
    'Querecotillo',
    'Salitral',
    'Sullana'
  ],
  'Talara': [
    'El Alto',
    'La Brea',
    'Lobitos',
    'Los Organos',
    'Mancora',
    'Pariñas'
  ],
  'Sechura': [
    'Bellavista de la Unión',
    'Bernal',
    'Cristo Nos Valga',
    'Rinconada Llícuar',
    'Sechura',
    'Vice'
  ],

  // Puno
  'Puno': [
    'Acora',
    'Amantani',
    'Atuncolla',
    'Capachica',
    'Chucuito',
    'Coata',
    'Huata',
    'Mañazo',
    'Paucarcolla',
    'Pichacani',
    'Platería',
    'Puno',
    'San Antonio',
    'Tiquillaca',
    'Vilque'
  ],
  'Azángaro': [
    'Achaya',
    'Arapa',
    'Asillo',
    'Azángaro',
    'Caminaca',
    'Chupa',
    'José Domingo Choquehuanca',
    'Muñani',
    'Potoni',
    'Saman',
    'San Anton',
    'San José',
    'San Juan de Salinas',
    'Santiago de Pupuja',
    'Tirapata'
  ],
  'Carabaya': [
    'Ajoyani',
    'Ayapata',
    'Coasa',
    'Corani',
    'Crucero',
    'Ituata',
    'Macusani',
    'Ollachea',
    'San Gabán',
    'Usicayos'
  ],
  'Chucuito': [
    'Desaguadero',
    'Huacullani',
    'Juli',
    'Kelluyo',
    'Pisacoma',
    'Pomata',
    'Zepita'
  ],
  'El Collao': ['Capaso', 'Conduriri', 'Ilave', 'Pilcuyo', 'Santa Rosa'],
  'Huancané': [
    'Cojata',
    'Huancane',
    'Huatasani',
    'Inchupalla',
    'Pusi',
    'Rosaspata',
    'Taraco',
    'Vilque Chico'
  ],
  'Lampa': [
    'Cabanilla',
    'Calapuja',
    'Lampa',
    'Nicasio',
    'Ocuviri',
    'Palca',
    'Paratia',
    'Pucara',
    'Santa Lucia',
    'Vilavila'
  ],
  'Melgar': [
    'Antauta',
    'Ayaviri',
    'Cupi',
    'Llalli',
    'Macari',
    'Nuñoa',
    'Orurillo',
    'Santa Rosa',
    'Umachiri'
  ],
  'Moho': ['Conima', 'Huayrapata', 'Moho', 'Tilali'],
  'San Antonio de Putina': [
    'Ananea',
    'Pedro Vilca Apaza',
    'Putina',
    'Quilcapuncu',
    'Sina'
  ],
  'San Román': ['Cabana', 'Cabanillas', 'Caracoto', 'Juliaca'],
  'Sandia': [
    'Alto Inambari',
    'Cuyocuyo',
    'Limbani',
    'Patambuco',
    'Phara',
    'Quiaca',
    'San Juan del Oro',
    'Sandia',
    'Yanahuaya'
  ],
  'Yunguyo': [
    'Anapia',
    'Copani',
    'Cuturapi',
    'Ollaraya',
    'Tinicachi',
    'Unicachi'
  ],

  // San Martín
  'Moyobamba': [
    'Calzada',
    'Habana',
    'Jepelacio',
    'Moyobamba',
    'Soritor',
    'Yantalo'
  ],
  'Bellavista': [
    'Alto Biavo',
    'Bajo Biavo',
    'Bellavista',
    'Huallaga',
    'San Pablo',
    'San Rafael'
  ],
  'El Dorado': [
    'Agua Blanca',
    'San José de Sisa',
    'San Martín',
    'Santa Rosa',
    'Shatoja'
  ],
  'Huallaga': [
    'Alto Saposoa',
    'El Eslabón',
    'Piscoyacu',
    'Sacanche',
    'Saposoa'
  ],
  'Lamas': [
    'Alonso de Alvarado',
    'Barranquita',
    'Caynarachi',
    'Cuñumbuqui',
    'Lamas',
    'Pinto Recodo',
    'Rumisapa',
    'San Roque de Cumbaza',
    'Shanao',
    'Tabalosos',
    'Zapatero'
  ],
  'Mariscal Cáceres': [
    'Campanilla',
    'Huicungo',
    'Juanjuí',
    'Pachiza',
    'Pajarillo'
  ],
  'Picota': [
    'Buenos Aires',
    'Caspisapa',
    'Picota',
    'Pilluana',
    'Pucacaca',
    'San Cristóbal',
    'San Hilarión',
    'Shamboyacu',
    'Tingo de Ponasa',
    'Tres Unidos'
  ],
  'Rioja': [
    'Awajun',
    'Elias Soplin Vargas',
    'Nueva Cajamarca',
    'Pardo Miguel',
    'Posic',
    'Rioja',
    'San Fernando',
    'Yorongos',
    'Yuracyacu'
  ],
  'San Martín': [
    'Alberto Leveau',
    'Cacatachi',
    'Chazuta',
    'Chipurana',
    'El Porvenir',
    'Huimbayoc',
    'Juan Guerra',
    'La Banda de Shilcayo',
    'Morales',
    'Papaplaya',
    'San Antonio',
    'Sauce',
    'Shapaja',
    'Tarapoto'
  ],
  'Tocache': ['Nuevo Progreso', 'Polvora', 'Shunte', 'Tocache', 'Uchiza'],

  // Tacna
  'Tacna': [
    'Alto de la Alianza',
    'Calana',
    'Ciudad Nueva',
    'Inclan',
    'Pachia',
    'Palca',
    'Pocollay',
    'Sama',
    'Tacna',
    'Coronel Gregorio Albarracín Lanchipa'
  ],
  'Candarave': [
    'Cairani',
    'Camilaca',
    'Candarave',
    'Curibaya',
    'Huanuara',
    'Quilahuani'
  ],
  'Jorge Basadre': ['Ilabaya', 'Ite', 'Locumba'],
  'Tarata': [
    'Chucatamani',
    'Estique',
    'Estique-Pampa',
    'Sitajara',
    'Susapaya',
    'Tarata',
    'Tarucachi',
    'Ticaco'
  ],

  // Tumbes
  'Tumbes': [
    'Corrales',
    'La Cruz',
    'Pampas de Hospital',
    'San Jacinto',
    'San Juan de la Virgen',
    'Tumbes'
  ],
  'Contralmirante Villar': ['Casanova', 'Matapalo', 'Zarumilla'],
  'Zarumilla': ['Aguas Verdes', 'Huaquillas', 'Papayal', 'Zarumilla'],

  // Ucayali
  'Coronel Portillo': [
    'Calleria',
    'Campoverde',
    'Iparia',
    'Masisea',
    'Nueva Requena',
    'Yarinacocha'
  ],
  'Atalaya': ['Raymondi', 'Sepahua', 'Tahuania', 'Yurua'],
  'Padre Abad': ['Alexander Von Humboldt', 'Curimana', 'Irazola', 'Padre Abad'],
  'Purús': ['Purús']
};
